Lesson 4 Practice
========================================================

***

### price vs. x


```{r }
library(ggplot2)
data("diamonds")
ggplot(aes(x = x, y = price), data = diamonds) + 
  geom_point(alpha = 1/20)  
```

***

### Correlations

```{r }
with(diamonds, cor.test(x, price))
with(diamonds, cor.test(y, price))
with(diamonds, cor.test(z, price))
```

***

### price vs depth  

```{r }
ggplot(aes(x = depth, y = price), data = diamonds) +
  geom_point(alpha = 1/20)
```

***

### adjustments

```{r }
ggplot(aes(x = depth, y = price), data = diamonds) +
  geom_point(alpha = 1/100) +
  scale_x_continuous(breaks = seq(0, 80, 2))
```

***

### correlations  

```{r }
with(diamonds, cor.test(depth, price))
```

***

### price vs carat

```{r }
ggplot(aes(x = carat, y = price), data = diamonds) + 
  geom_point(alpha = 1/20) +
  xlim(0, quantile(diamonds$carat, 0.99)) +
  ylim(0, quantile(diamonds$price, 0.99))
```

***

### price vs volume

```{r }
diamonds$volume <- diamonds$x * diamonds$y * diamonds$z
ggplot(aes(x = volume, y = price), data = diamonds) + 
  geom_point()
```

***

### Title

```{r }
with(subset(diamonds, (volume > 0)  & (volume <= 800)), cor.test(volume, price))
```

***

### adjustments

```{r }
ggplot(aes(x = volume, y = price), data = subset(diamonds, (volume > 0) & (volume <= 800))) + 
  geom_point(alpha = 1/20) + 
  geom_smooth()
```

***

### mean price by clarity

```{r }
library(dplyr)
diamondsByClarity <- diamonds %>%
                      group_by(clarity) %>%
                      summarise(mean_price = mean(price),
                                median_price = median(price),
                                min_price = min(price),
                                max_price = max(price),
                                n = n()) %>%
                      arrange(clarity)

head(diamondsByClarity)
```

***

### bar charts of mean price

```{r }
diamonds_by_clarity <- group_by(diamonds, clarity)
diamonds_mp_by_clarity <- summarise(diamonds_by_clarity, mean_price = mean(price))

diamonds_by_color <- group_by(diamonds, color)
diamonds_mp_by_color <- summarise(diamonds_by_color, mean_price = mean(price))


p1 <- ggplot(aes(x = clarity, y = mean_price, fill = clarity), data = diamonds_mp_by_clarity) +
  geom_bar(stat = "identity")
p2 <- ggplot(aes(x = color, y = mean_price, fill = color), data = diamonds_mp_by_color) +
  geom_bar(stat = "identity")

library(gridExtra)
grid.arrange(p1, p2, ncol = 2)
```
