Lesson 4 Practice
========================================================

***

### price hist with facet and color

```{r }
library(ggplot2)
data("diamonds")
ggplot(aes(x = price, color = cut), data = diamonds) + 
  geom_histogram(aes(fill = cut)) + 
  facet_wrap( ~ color)
```

***

### Price vs Table colored by Cut

```{r }
ggplot(aes(x = table, y = price), data = diamonds) +
  geom_point(aes(color = cut), alpha = 1/10)
```

***

### price vs volume and clarity  

```{r }
diamonds <- transform(diamonds, volume = x * y * z)
ggplot(aes(x = volume, y = price), data = diamonds) +
  geom_point(aes(color = clarity)) +
  scale_y_log10() +
  xlim(0, quantile(diamonds$volume, 0.99)) 
```

***

### Proportion of Friendships Initiated

```{r }
pf <- read.csv("pseudo_facebook.tsv", sep='\t')
pf <- transform(pf, prop_initiated = friendships_initiated / friend_count)
```

***

### prop_initiated vs tenure

```{r }
pf$year_joined <- 2014 - floor(pf$tenure / 365)
pf$year_joined.bucket <- cut(pf$year_joined, c(2004, 2009, 2011, 2012, 2014))
ggplot(aes(x = tenure, y = prop_initiated, color = year_joined.bucket), data = pf) +
  geom_line(stat = 'summary', fun.y = median)
```

***

### smoothing
```{r }
ggplot(aes(x = tenure, y = prop_initiated, color = year_joined.bucket), data = pf) +
  geom_line(stat = 'summary', fun.y = median) +
  geom_smooth()
```

***

### Largest Group Mean prop_initiated

```{r }
by(pf$prop_initiated, pf$year_joined.bucket, summary)
```

***

### Price/Carat Binned, Faceted, & Colored

```{r }
ggplot(aes(x = cut, y = price / carat, color = color), data = diamonds) +
  geom_jitter() +
  facet_wrap( ~ clarity)
```

